# @file Makefile
# 
MAKE = make
BUILD = lib
TARGET = libmdwsys.a

# sources 
sources = \
	signals.cpp

# read common rules
include $(MEADOW_HOME)/etc/Makefile.template

# customizations
$(TARGET): $(sources)
